### ISSUE TITLE
Modul lässt sich unter oxid 6.5 nicht installieren

### ISSUE THREAD

**Issue by Doumanix** [d3datadevelopment/PDFDocuments#1]
Composer Fehlermeldung: 

  Problem 1
    - d3/pdfdocuments[1.0.0.0, ..., 1.0.1.0] require oxid-esales/oxideshop-ce 6.3 - 6.5 -> found oxid-esales/oxideshop-ce[v6.3.0, ..., v6.5.6] but the package is fixed to v6.12.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - d3/pdfdocuments 1.0.2.0 requires oxid-esales/oxideshop-ce 6.3 - 6.8 -> found oxid-esales/oxideshop-ce[v6.3.0, ..., v6.8.0] but the package is fixed to v6.12.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires d3/pdfdocuments ^1.0 -> satisfiable by d3/pdfdocuments[1.0.0.0, 1.0.1.0, 1.0.2.0].

Wäre cool, wenn man das Modul auch unter einer aktuellen Version zum Laufen bringen könnte :-)

**Comment by d3datadev** [comment]
Hallo Doumanix,

Deine Meldung tauchte leider jetzt erst bei uns auf. Sorry dafür.

Unabhängig dessen hatten wir das Plugin mittlerweile auch bis OXID 6.5.1 freigegeben. Da kannst es also gern verwenden.
