### ISSUE TITLE
Fehlermeldung beim PDF-Generieren unter PHP 8.1.xx

### ISSUE THREAD

**Issue by Doumanix** [d3datadevelopment/PDFDocuments#2]
Ich hatte das Problem auch schon unter oxid CE 6.5.0 festgestellt, und hatte gehofft, dass es im Laufe der Zeit einen Fix / ein Update gibt. 
Aber nach wie vor ist es bei mir so, dass wenn ich auf PHP 8.1.xx (aktuell 8.1.26) umstelle, wird kein PDF Download ausgelöst. In den Logs finden sich dann solche Einträge: 

`[Mon Dec 18 20:55:00.003657 2023] [fcgid:warn] [pid 2716123:tid 140158313678592] [client xx.xx.xx.xx:0] mod_fcgid: stderr: PHP Warning:  Cannot modify header information - headers already sent by (output started at /var/www/vhosts/mydomain/source/modules/d3/modcfg/Application/Model/d3filesystem.php:3) in /var/www/vhosts/mydomain/vendor/oxid-esales/oxideshop-ce/source/Core/Header.php on line 46, referer: https://mydomain/admin/index.php?editlanguage=0&force_admin_sid=allcsgiuho5ajb6tjr8vd442no&stoken=A05E2535&
`

Egal, ob ich fastcgi oder php-fpm verwende.  
/tmp ordner wurde nach jeder Umstellung von PHP gelöscht. 

Mit PHP 7.4.33 funktioniert das Modul einwandfrei.

**Comment by SeifertDaniel** [comment]
Hallo Doumanix,

dank Dir für Deinen Hinweis.

Der Download kann nicht gestartet werden, da schon vorher eine Ausgabe passiert (die auslösende Stelle ist oben benannt). Die Lösung wird demnach vermutlich sein, die vorherige Ausgabe zu beseitigen oder zu unterbinden. 

Ich gehe davon aus, dass die Ausgabe systemabhängig ist. Daher werde ich die wahrscheinlich nicht selbst reproduzieren können.

Hast Du eine Möglichkeit, an diese besagte Meldung (möglicherweise eine Fehlermeldung) zu kommen und die hier zu posten? Kleine Hilfestellung: Die PDF-Generierung läuft in einem versteckten iFrame in der Nähe der Buttons ab. Wenn Du Dir den iFrame sichtbar konfigurierst, dürftest Du die Meldung sehen.

Wenn Du Unterstützung brauchst, melde Dich bitte unter support@shopmodule.com.

**Comment by Doumanix** [comment]
Hallo @SeifertDaniel ,

danke für das schnelle Feedback. Der Tipp hat geholfen. Es scheint am fehlenden ionCube Loader zu liegen. In PHP 7.x war das in Plesk mit dabei, für PHP 8.x wohl nicht mehr. 
Ich mach mich mal auf die Suche, den Fehler zu beheben.

**Comment by Doumanix** [comment]
Hi nochmal,

stolpere jetzt leider über einen weiteren Fehler: 

`The file /var/www/vhosts/mydomain/source/modules/d3/modcfg/Application/Model/d3filesystem.php encoded as type [1/71] cannot be decoded by this version of the ionCube Loader.\n in Unknown on line 0'`

Habe aktuell die v13.0.2 des Loaders aktiviert (wohl die aktuellste). Kommt es damit zu bekannten Problemen?

**Comment by SeifertDaniel** [comment]
Wir kommen der Sache näher:

Ab PHP 8 waren wir gezwungen, von ionCube zu SourceGuardian zu wechseln. Prüfe daher bitte Folgendes:

- steht Dir der SourceGuardian Loader auf dem Webserver und in der CLI zur Verfügung (entsprechender Abschnitt in der phpinfo-Auswertung)?
- hast Du eine php8-kompatible Version unseres Connectors installiert? Lass Dir dazu in Composer die Versionsnummer anzeigen: "composer show d3/modcfg". Die Versionsnummer muss auf *80 enden.

Freue mich auf Deine Rückmeldung.

**Comment by Doumanix** [comment]
Hmmm... was mir mal als erstes aufgefallen ist: 
Hier ist v1.1.0.0 in der URL, die Anleitung beinhaltet aber v1.0.1.0 https://docs.oxidmodule.com/PDF-Dokumente/1.1.0.0/installation/Neuinstallation/Modul_hinzufuegen.html 
Die Installanleitung sagt auch `php composer require d3/pdfdocuments:^1.0.1.0 --update-no-dev`  aber in https://github.com/d3datadevelopment/PDFDocuments steht  `composer require d3/pdfdocuments:^1.0 --update-no-dev` (ok, marginaler Unterschied. 

Ein Hinweis auf die neuen Anforderungen mit PHP8 wären sicher in der Doku oder in der readme.md hilfreich. 
Ich hatte nach deinem Hinweis in einer Testinstallation erst mal die Version von modcfg gecheckt. Passte nicht. 
Also: alle d3 Module entfernt und dann versucht neu zu installieren. 
Daraufhin kam eine Fehlermeldung, ich bräuchte d3/modcfg in einer passenden Version. Als ich dann versucht habe isoliert d3/modcfg 6.1.2.080 zu installieren, kam Folgendes: 

```
  Problem 1
    - Root composer.json requires d3/modcfg 6.1.2.080 -> satisfiable by d3/modcfg[6.1.2.080].
    - d3/modcfg 6.1.2.080 requires ext-sourceguardian * -> it is missing from your system. Install or enable PHP's sourceguardian extension.
```

Was ja am Ende wieder zu deinem Hinweis mit sourceguardian führt.
Ich versuche das mal in Plesk zu installieren. Das ist aber eine andere Baustelle und ich vermute, damit ist das Rätsel hier gelöst.

**Comment by Doumanix** [comment]
Ok, habs geschafft. 
Falls es jemandem hilft bei der Installation unter Plesk: https://support.plesk.com/hc/en-us/articles/13302968117143-How-to-install-SourceGuardian-PHP-extension-
Man muss natürlich die PHP-Versionen anpassen, aber ansonsten klappt das Prozedere schon. 

Dann muss noch in der PHP-Konfiguration der Domain mit `extension=ixed.8.1.lin`  die Extension aktiviert werden. 

Und schon :-) geht auch d3/pdfdocuments Modul wieder. 

Danke nochmal, @SeifertDaniel für deine Hilfe!

**Comment by SeifertDaniel** [comment]
Dank Dir für den Hinweis auf die Dokumentationsdifferenzen. Ich hab die (sofern die inhaltlich relevant sind) korrigiert und auf den aktuellen Stand gebracht. Damit einher geht auch ein neues Release 1.0.4.0 und eine neue Dokumentation (https://docs.oxidmodule.com/PDF-Dokumente/1.0.4.0/). 

Die nötigen Paketupdates bei Änderung der PHP-Versionsnummer betrifft nicht speziell dieses Modul und wäre damit in dieser Dokumentation auch nicht relevant. Es fehlt im OXID-Umfeld aber so ein grundsätzlicher Updateleitfaden, in dem auch solche Sachen beschrieben sind. Ich habe mir aber vorgemerkt, dass wir in unseren Moduldokumentationen zukünftig ganz allgemein auf Änderungen der Systemumgebung eingehen.

Damit wünsche ich Dir viel Erfolg mit dem Modul.
